# Generated by Django 5.1.5 on 2025-01-27 15:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('taille', models.CharField(choices=[('M', 'Moyen'), ('L', 'Large'), ('XL', 'Extra Large')], max_length=10)),
                ('poids', models.FloatField(help_text='Poids en grammes')),
                ('quantite_stock', models.PositiveIntegerField(default=0)),
                ('couleur', models.CharField(choices=[('Jaune', 'Jaune'), ('Rouge', 'Rouge'), ('Vert', 'Vert'), ('Bleu', 'Bleu')], default='Jaune', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Sandwich',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('taille', models.CharField(choices=[('M', 'Moyen'), ('L', 'Large'), ('XL', 'Extra Large')], max_length=10)),
                ('poids_total', models.FloatField(default=0, help_text='Poids total du sandwich en grammes')),
                ('produits', models.ManyToManyField(to='commandes.produit')),
            ],
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField(default=1)),
                ('poids_total', models.FloatField(default=0, help_text='Poids total de la commande en grammes')),
                ('status', models.CharField(choices=[('en attente', 'En attente'), ('validée', 'Validée')], default='en attente', max_length=20)),
                ('code_barre', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('sandwich', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commandes.sandwich')),
            ],
        ),
    ]
