# Generated by Django 5.1.5 on 2025-01-30 11:06

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Addstock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('taille', models.CharField(max_length=10)),
                ('quantite_stock', models.PositiveIntegerField(default=0)),
                ('date_heure', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('taille', models.CharField(choices=[('S', 'Petit'), ('M', 'Moyen'), ('L', 'Large')], max_length=10)),
                ('poids', models.FloatField(help_text='Poids en grammes')),
                ('quantite_stock', models.PositiveIntegerField(default=0)),
                ('couleur', models.CharField(choices=[('Jaune', 'Jaune'), ('Rouge', 'Rouge'), ('Vert', 'Vert'), ('Bleu', 'Bleu')], default='Jaune', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Temperature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_heure', models.DateTimeField(auto_now_add=True)),
                ('temperature', models.FloatField(help_text='Température en degrés Celsius')),
                ('humidite', models.FloatField(help_text='Humidité en pourcentage')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Sandwich',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('taille', models.CharField(choices=[('S', 'Petit'), ('M', 'Moyen'), ('L', 'Large')], max_length=10)),
                ('poids_total', models.FloatField(default=0)),
                ('produits', models.ManyToManyField(to='commandes.produit')),
            ],
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField(default=1)),
                ('poids_total', models.FloatField(default=0, help_text='Poids total de la commande en grammes')),
                ('status', models.CharField(choices=[('en attente', 'En attente'), ('ticket imprimé', 'Ticket imprimé'), ('validée', 'Validée'), ('en cuisson', 'En cuisson'), ('terminée', 'Terminée')], default='en attente', max_length=20)),
                ('date_commande', models.DateTimeField(auto_now_add=True)),
                ('sandwich', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commandes.sandwich')),
            ],
        ),
    ]
