# Generated by Django 5.1.5 on 2025-01-27 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='date_commande',
            field=models.DateTimeField(auto_now_add=True, default='2024-01-27 00:00:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='commande',
            name='temps_cuisson_total',
            field=models.PositiveIntegerField(default=0, help_text='Temps de cuisson total en secondes'),
        ),
        migrations.AddField(
            model_name='produit',
            name='temps_cuisson',
            field=models.PositiveIntegerField(default=0, help_text='Temps de cuisson en secondes'),
        ),
        migrations.AddField(
            model_name='sandwich',
            name='temps_cuisson',
            field=models.PositiveIntegerField(default=0, help_text='Temps de cuisson total en secondes'),
        ),
        migrations.AlterField(
            model_name='commande',
            name='status',
            field=models.CharField(choices=[('en attente', 'En attente'), ('validée', 'Validée'), ('en cuisson', 'En cuisson'), ('terminée', 'Terminée')], default='en attente', max_length=20),
        ),
        migrations.AlterField(
            model_name='produit',
            name='taille',
            field=models.CharField(choices=[('S', 'Petit'), ('M', 'Moyen'), ('L', 'Large')], max_length=10),
        ),
        migrations.AlterField(
            model_name='sandwich',
            name='taille',
            field=models.CharField(choices=[('S', 'Petit'), ('M', 'Moyen'), ('L', 'Large')], max_length=10),
        ),
    ]
