# Generated by Django 5.1.5 on 2025-01-27 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0002_commande_date_commande_commande_temps_cuisson_total_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sandwich',
            name='poids_total',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='sandwich',
            name='temps_cuisson',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
