# Generated by Django 5.1.5 on 2025-01-28 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0003_alter_sandwich_poids_total_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commande',
            name='code_barre',
        ),
        migrations.RemoveField(
            model_name='commande',
            name='temps_cuisson_total',
        ),
        migrations.RemoveField(
            model_name='produit',
            name='temps_cuisson',
        ),
        migrations.AlterField(
            model_name='commande',
            name='status',
            field=models.CharField(choices=[('en attente', 'En attente'), ('ticket imprimé', 'Ticket imprimé'), ('validée', 'Validée'), ('en cuisson', 'En cuisson'), ('terminée', 'Terminée')], default='en attente', max_length=20),
        ),
        migrations.AlterField(
            model_name='sandwich',
            name='temps_cuisson',
            field=models.PositiveIntegerField(default=0, help_text='Temps de cuisson total du sandwich (secondes)'),
        ),
    ]
