# Generated by Django 5.1.5 on 2025-01-29 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0004_remove_commande_code_barre_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConditionsMeteo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_heure', models.DateTimeField(auto_now_add=True)),
                ('temperature', models.FloatField(help_text='Température en degrés Celsius')),
                ('humidite', models.FloatField(help_text='Humidité en pourcentage')),
            ],
        ),
    ]
