# Generated by Django 5.1.5 on 2025-01-29 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0005_conditionsmeteo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ConditionsMeteo',
            new_name='Temperature',
        ),
    ]
