# Generated by Django 5.1.5 on 2025-01-29 13:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0006_rename_conditionsmeteo_temperature'),
    ]

    operations = [
        migrations.AddField(
            model_name='temperature',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
