# Generated by Django 5.1.5 on 2025-01-29 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0007_temperature_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Addstock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('taille', models.CharField(max_length=10)),
                ('quantite_stock', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='produit',
            name='taille',
            field=models.CharField(choices=[('S', 'Petit'), ('L', 'Large')], max_length=10),
        ),
        migrations.AlterField(
            model_name='sandwich',
            name='taille',
            field=models.CharField(choices=[('S', 'Petit'), ('L', 'Large')], max_length=10),
        ),
    ]
