# Generated by Django 5.1.5 on 2025-01-30 09:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0008_addstock_alter_produit_taille_alter_sandwich_taille'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConditionsMeteo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_heure', models.DateTimeField(auto_now_add=True)),
                ('temperature', models.FloatField(help_text='Température en degrés Celsius')),
                ('humidite', models.FloatField(help_text='Humidité en pourcentage')),
            ],
        ),
        migrations.RemoveField(
            model_name='sandwich',
            name='temps_cuisson',
        ),
        migrations.AddField(
            model_name='addstock',
            name='date_heure',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='produit',
            name='taille',
            field=models.CharField(choices=[('S', 'Petit'), ('M', 'Moyen'), ('L', 'Large')], max_length=10),
        ),
        migrations.AlterField(
            model_name='sandwich',
            name='taille',
            field=models.CharField(choices=[('S', 'Petit'), ('M', 'Moyen'), ('L', 'Large')], max_length=10),
        ),
    ]
