# Generated by Django 5.1.5 on 2025-01-29 21:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0008_addstock_alter_produit_taille_alter_sandwich_taille'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sandwich',
            name='temps_cuisson',
        ),
        migrations.AddField(
            model_name='addstock',
            name='date_heure',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='produit',
            name='nom',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='produit',
            name='taille',
            field=models.CharField(choices=[('S', 'Petit'), ('M', 'Moyen'), ('L', 'Large')], max_length=10),
        ),
        migrations.AlterField(
            model_name='sandwich',
            name='taille',
            field=models.CharField(choices=[('S', 'Petit'), ('M', 'Moyen'), ('L', 'Large')], max_length=10),
        ),
    ]
