name: Django CI/CD

on: push

jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python in a virtual environment
      run: |
        if [[ `uname` != "Darwin" ]]; then sudo apt-get -y install python3-venv; fi
        python3 -m venv .venv

    - name: Install dependencies
      run: |
        source .venv/bin/activate
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Apply Migrations
      run: |
        source .venv/bin/activate
        python manage.py migrate

    - name: Collect Static Files
      run: |
        source .venv/bin/activate
        python manage.py collectstatic --noinput

    - name: Run Tests
      run: |
        source .venv/bin/activate
        python manage.py test

    - name: Run Server
      if: success() && github.ref == 'refs/heads/main'
      run: |
        source .venv/bin/activate
        killall python || true  # Arrête tout serveur Python en cours
        RUNNER_TRACKING_ID="" && (nohup daphne -b 0.0.0.0 -p 8000 fablab_api.asgi:application >> log.txt &)

