name: Django Test

on: push

jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
      with:
        path: './test'

    - name: Set up Python in a virtual environment
      run: |
        if [[ `uname` != "Darwin" ]]; then sudo apt-get -y install python3-venv; fi
        python3 -m venv .venv

    - name: Install dependencies
      run: |
        source .venv/bin/activate
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Apply Migrations
      run: |
        pwd
        source .venv/bin/activate
        python manage.py makemigrations
        python manage.py migrate

    - name: Run Tests
      run: |
        source .venv/bin/activate
        python manage.py test

